; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = attiny85
framework = arduino
lib_deps = 
    nickcengel/TinyWireSio

[env:t85VICONTROL]
build_flags = 
    -D I2C_SLAVE_ADDR=0x26
    -D ROLE = 0x01
    -D WITH_CURRENT_LIMITER = 0x01

[env:t85NTFCONTROL]
build_flags = 
    -D I2C_SLAVE_ADDR=0x27
    -D ROLE = 0x02
